### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by thien-ds** [yc4ny/NeRSemble_Training#1]
First of all, I would like to express my sincere gratitude for your contributions to the Gaussian Head Avatars project. The code is very detailed and informative, and it has been extremely helpful to me in my research. Secondly, I am having trouble accessing the Google Drive link to download the checkpoints. Could you please provide me with an alternative link?

**Comment by yc4ny** [comment]
Hi, I have updated the Google Drive link. Thanks. 
https://drive.google.com/drive/folders/1o8JeQirndKCpL1fvyhp-GsQeBZjgv22i
