### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by thien-ds** [yc4ny/NeRSemble_Training#2]
Can you provide more information about hardware for training models? I am currently using an Nvidia Quadro RTX 4000  8 GB, but it seems to be insufficient for my needs and is causing out-of-memory errors.

![image](https://github.com/yc4ny/NeRSemble_Preprocess/assets/141995623/f519bd00-ff70-4ddd-849c-14fe6840db59)

**Comment by yc4ny** [comment]
Hi, 8GB is too small to train the models. I ran on a 3090 24GB graphics card. You may adjust the number of gaussians but it will have significant impact on quality. I think at least a 12GB is required for appropriate training.
