### ISSUE TITLE
Camera parameters

### ISSUE THREAD

**Issue by Buzzalter** [yc4ny/NeRSemble_Training#3]
Hey, great work!

Do you know of a way to generate the camera parameters (intrinsics/extrinsics) without pre-calibrating the camera? Or the best way to estimate them? I can see the GHA author in the 3DMM repo basically states these when they preprocess a monocular video but i assume this isn’t a one size fits all guess.

**Comment by yc4ny** [comment]
@Buzzalter  
Hi, thank for your interest in this repo.
Do you mean obtaining camera parameters with your custom data?
I'm also not so clear of what you mean by pre-calibrating the camera, we normally calibrate to obtain the camera parameters.  A standard way of obtaining the camera parameters (also how the NeRSemble authors did) is to use Colmap and run SfM.

**Comment by CscotfordMV** [comment]
Yes, I mean given custom data how to calculate the camera intrinsics/extrinsics.
I understand it is possible to get this information by calibrating the camera prior to recording by holding up a checkerboard pattern to the camera and employing an opencv function.
I will try COLMAP to process them, but I have found it to be unreliable in the past. Maybe I should relax the matching conditions

**Comment by Buzzalter** [comment]
Yes, I mean calculating the camera intrinsics and extrinsics from custom data. By precalibrating I mean holding up a checkerboard to the camera and employing an opencv function.
I have attempted to use Colmap before but I found it a little unreliable as it doesn't always plot the 3d space with the correct coordinates or sense of unity, but I will have another go

**Comment by yc4ny** [comment]
@Buzzalter 

I see what you mean. As you already know, its best to pre calibrate using Zhang's method (checkerboard) and feed the obtained intrinsic parameters to Colmap and it will refine the camera extrinsics. I'm not so familiar with Unity so it would be difficult to give you advice on that matter. Thanks.
